### ISSUE TITLE
Please add a maintainer

### ISSUE THREAD

**Issue by brandones** [lxyu/kindle-clippings#18]
Looks like this repo has fallen out of maintenance. Could you please hand over maintenance to someone else? If no one else is enthusiastic about doing it, I could.

**Comment by sanjaymaniam** [comment]
I wrote a little [script](https://github.com/ultrasanjay/kindler) for myself. Not as good, but does the trick for me. That said, I'm totally game for co-maintaining a fork of this project, or building one from scratch (there seem to be license-related issues here).

Let me know!

**Comment by brandones** [comment]
Hey @ultrasanjay ! Sounds great. I'll open a PR or two this weekend.
