### ISSUE TITLE
msgpack instead of JSON?

### ISSUE THREAD

**Issue by tevino** [lxyu/kindle-clippings#2]
I know msgpack is great, but I don't see any significant benefits in this project. :no_mouth: 
Isn't that great if this project comes with no external dependency? :smiley:

**Comment by tevino** [comment]
@lxyu

**Comment by lxyu** [comment]
Yah you're right, it don't benefit much, though I don't think a dependency matters much either.

Feel free to send me a pull request~

:smile:

**Comment by tevino** [comment]
Here it is: #3 :smiley:

**Comment by lxyu** [comment]
Merged, thanks!
